### ISSUE TITLE
Installation steps don't complete due to an error

### ISSUE THREAD

**Issue by prawnsalad** [adonisjs/core#3159] opened 2021-09-11 22:22 UTC
~~~shell
$ npm init adonis-ts-app@latest hello-world
npx: installed 193 in 10.756s
    _       _             _         _
   / \   __| | ___  _ __ (_)___    | |___
  / _ \ / _` |/ _ \| '_ \| / __|_  | / __|
 / ___ \ (_| | (_) | | | | \__ \ |_| \__ \
/_/   \_\__,_|\___/|_| |_|_|___/\___/|___/


CUSTOMIZE PROJECT
❯ Select the project structure · web
❯ Enter the project name · hello-world
❯ Setup eslint? (y/N) · false
❯ Configure webpack encore for compiling frontend assets? (y/N) · false

RUNNING TASKS
❯ Scaffold project 41 ms
❯ Install dependencies 22 s
❯ Configure installed packages 2.95 ms
  Package subpath './package.json' is not defined by "exports" in /private/tmp/hello-world/node_modules/@adonisjs/core/package.json

[ error ]  Unable to create project. Cleaning up
~~~

Same happens with yarn. Same with all available options in the setup above.

## Package version
N/A

## Node.js and npm version
~~~shell
23:19:41 [darren@mb-2 /tmp] $ node -v
v14.5.0
23:21:10 [darren@mb-2 /tmp] $ npm -v
6.14.5
23:21:12 [darren@mb-2 /tmp] $
~~~

## Sample Code (to reproduce the issue)
N/A

**Comment by thetutlage** [comment] 2021-09-13 02:55
Duplicate of https://github.com/adonisjs/core/issues/3109

**Closed by thetutlage** 2021-09-13 02:55 UTC

**Comment by OrkhanAlikhanov** [comment] 2021-12-18 14:22
What is remedy?
