### ISSUE TITLE
Nested resources use pluralised ids, and last child in resource uses only id

### ISSUE THREAD

**Issue by TynesideGroup** [adonisjs/core#797] opened 2018-02-20 15:56 UTC
Nested resources work brilliantly, but one pain point I have with them is how the `id` of each item within a nested resource is accessed from `params`.

As an example, lets say you have a nested resource for `User`s and `Car`s e.g.:
```js
Route.resource('users.cars', 'CarController')
```

To view a specific `Car` for a specific `User` you would send a GET request to something like `users/1/cars/1` and `params` would be `{ users_id: 1, id: 1 }`.

I do not think the pluralisation of `user_id` makes sense here as you are accessing a single `Car` for a single `User`. It is also unclear at first glance in the controller method what `id` would refer to, particularly as you are working with multiple `id`s.

As such, I believe `params` for nested resource routes should look more like `{ user_id: 1, car_id: 1 }`.

A more complex example is one I have in my ongoing SAAS project:
```js
Route
  .resource('properties.tenancies.tenants.application-form', 'ApplicationFormController')
  .apiOnly()
```

In this case, `params` looks something like:
```js
{
  properties_id: 1,
  tenancies_id: 1,
  tenants_id: 1,
  id: 1
}
```

When working with such a level of nesting in a controller and complex methods it would be much clearer to use the singular version of `id`s and to explicitly change `id` to `application_form_id` so that it is clear what `id` is being used:
```js
{
  property_id: 1,
  tenancy_id: 1,
  tenant_id: 1,
  application_form_id: 1
}
```

I would consider any fix for this a breaking change as it would impact almost every project using nested resource routes. As such perhaps it would be preferable to do the following if possible:

- Add the ability to use singular versions of `XXX_id` (for all levels of nesting, including the last child)
- Continue to accept pluralisation for the parent resource(s) and `id` for the last child, but mark them for deprecation in a future release
- Fully deprecate when you see fit

Any thoughts?

**Comment by RomainLanz** [comment] 2018-02-20 18:07
Thanks for the issue @liam-potter.

As stated before this should be fixed but it will create a breaking change in all running application.

One solution could be to deprecate the plural but keep it for compatibility while adding a singular version.

**Comment by liam-potter** [comment] 2018-02-20 18:59
@RomainLanz Agreed - I mentioned deprecation as a possible solution to prevent breaking changes at the bottom of my message.

Do you also agree the last child in the nested resource should be `model_id` rather than just `id`? I feel this will help make it clear what `id`you're actually using in the controller.

I'm happy for single resources to keep using `id` as there's no confusion there.

**Comment by thetutlage** [comment] 2018-02-21 08:02
Not a bug, since it was by design.

Also I don't think that the change can take place right now, since it is a breaking change with readability benefits only. 

Also if we are changing this, then we should also make the `model_id` camel case instead `modelId`

**Comment by liam-potter** [comment] 2018-02-21 09:39
I am aware this would have originally been by design, but I think the original design choice was not the best option as pluralisation of the ID is not correct - for each level in the nested resource you're only referencing a single item from that level.

Yes, I agree this change would only offer a readability benefit and would require breaking changes to implement. This is why me and @RomainLanz suggested keeping them (but marking them as deprecated for future removal) and adding the singular versions.

Out of curiosity, what are the reasons you believe we should use camelCase e.g. `tenancyId` rather than `tenancy_id`? Is this some sort of best practice?

Sorry if any of this sounds patronising - it's really not meant to!

**Comment by diego-lipinski-de-castro** [comment] 2018-03-19 12:33
Agree with all of @liam-potter pointer, no sense to be pluralized, and also keeping snakecase feels way way better

**Comment by liam-potter** [comment] 2018-06-11 09:41
@Atinux Agreed, it would be nice if we keep this this behaviour in 5.0 but mark it as deprecated (and then remove it in 6.0).

@thetutlage @RomainLanz Thoughts?

**Comment by thetutlage** [comment] 2018-06-11 10:16
Yes up for it. Also we can depreciate it another minor release and then remove it in `5.0`.

**Comment by begueradj** [comment] 2019-04-22 08:04
Breaking change for one letter ? This does not make sens to me.

**Comment by thetutlage** [comment] 2019-11-05 18:15
Going to incorporate `singular` param names. However, I would still call the final node identifier as `id`.

**Comment by TynesideGroup** [comment] 2019-11-06 10:43
@thetutlage More than happy with this - it's easy enough to remember that `id` either points to a resource or the "final" item in a nested resource.

Will you be keeping params as snake case e.g. `tenancy_id`, or moving to camel case `tenancyId` as per https://github.com/adonisjs/adonis-framework/issues/797#issuecomment-367243069? I think it would be better to keep snake case, unless the TS rewrite is also changing convention across the entire framework.

**Comment by thetutlage** [comment] 2019-11-06 11:11
I agree, going to `camelCase` isn't desired as of now. Also, by being `snake_case` and using `id`, we stay in sync with many other frameworks like Rails, Laravel and so on.

**Comment by thetutlage** [comment] 2020-07-26 08:56
Pretty late, but this has been fixed in v5. Closing it for now

**Closed by thetutlage** 2020-07-26 08:56 UTC
Labels: Priority: Medium, Semver: Alpha, Status: In Progress, Type: Enhancement
