### ISSUE TITLE
cannot create project by yarn create adonis-ts-app blog

### ISSUE THREAD

**Issue by ynl** [adonisjs/core#1261] opened 2020-07-18 14:00 UTC
![image](https://user-images.githubusercontent.com/5300032/87854114-f9400100-c941-11ea-954c-531c3281aefe.png)

**Comment by thetutlage** [comment] 2020-07-18 14:15
Closing, since you have not provided enough information. Dumping a terminal screenshot in the issue is not going to help anyone.

Create a new proper issue with

- The OS you are using
- Node version & npm version or yarn version
- Which command you executed to create the project

**Closed by thetutlage** 2020-07-18 14:15 UTC
Labels: triage
