### ISSUE TITLE
Getting an error for assets compilation with webpack-encore.

### ISSUE THREAD

**Issue by seekex** [adonisjs/core#4334] opened 2024-01-04 07:15 UTC
Getting error like this when run `node ace serve --watch` command.
![image](https://github.com/adonisjs/core/assets/71244401/edf8a4fe-5e58-4c8e-b97a-9026edb20a0c)

I have tried to update webpack , after update getting same error.

Node version "Node.js v18.17.1".

**Comment by RomainLanz** [comment] 2024-01-04 10:20
Hello @seekex! 👋

Thank you for reaching out. From the information provided, it appears that the issue is not directly related to AdonisJS. As you've mentioned, the problem occurred after updating webpack, and this is further indicated by the stack trace. Therefore, the issue seems to be associated with Webpack.

I recommend opening an issue in the Webpack repository to get more targeted assistance. This will help in addressing the problem more effectively with the expertise of the Webpack community.

**Comment by Julien-R44** [comment] 2024-01-15 13:02
Closing since no answers for OP. 

However, from memory, this was caused by a breaking change on Nodejs side. You need to rollback to node 16 or, better, update webpack, or use the `--openssl-legacy-provider` parameter. See https://www.codingbeautydev.com/blog/node-err-ossl-evp-unsupported

**Closed by Julien-R44** 2024-01-15 13:02 UTC
Labels: Type: Invalid
