### ISSUE TITLE
Route.matchers.uuid() should also include lowercase letters

### ISSUE THREAD

**Issue by ad-on-is** [adonisjs/core#3522] opened 2022-01-28 10:48 UTC
Currently the matcher is implemented like this

```js
public uuid(): { match: RegExp } {
    return { match: /^[0-9A-F]{8}-[0-9A-F]{4}-[0-9A-F]{4}-[0-9A-F]{4}-[0-9A-F]{12}$/ }
  }
```
Is there a reason why lowercase letters are not included? Otherwise it should be

```js
public uuid(): { match: RegExp } {
    return { match: /^[0-9A-Fa-f]{8}-[0-9A-Fa-f]{4}-[0-9A-Fa-f]{4}-[0-9A-Fa-f]{4}-[0-9A-Fa-f]{12}$/ }
  }
```

**Comment by RomainLanz** [comment] 2022-01-28 11:07
Hey @ad-on-is! 👋🏻 

This is a duplicate of https://github.com/adonisjs/http-server/issues/50.
Closing this to avoid spreading the discussion.

**Closed by RomainLanz** 2022-01-28 11:07 UTC
