### ISSUE TITLE
Cannot register route with "PUT" and "DELETE" method

### ISSUE THREAD

**Issue by hariprasath-yadav** [adonisjs/core#1207] opened 2020-02-19 14:23 UTC
## Package version
4.1

## Node.js and npm version
v12.14.1 and 6.13.4

## Sample Code (to reproduce the issue)
Route.route('/reference', 'Proj/Masters/ReferenceController.updateAll', ['PUT', 'PATCH']).as('reference.updateAll')
Route.delete('/reference', 'Proj/Masters/ReferenceController.destoryAll').as('reference.destoryAll')

Return Error with
Message: **Route not found PUT /reference**
Code: **404**

and

Message: **Route not found DELETE /reference**
Code: **404**

**Comment by thetutlage** [comment] 2020-02-19 14:50
Can you share the output of `adonis route:list` command?

**Comment by hariprasath-yadav** [comment] 2020-02-20 08:16
This is my routes
│ Route │ Verb(s) │ Handler │ Middleware │ Name │ Domain │
│ /check_auth │ HEAD,GET │ Closure │ auth │ /check_auth │ │
│ /login │ POST │ Proj/Masters/UserController.login │ │ /login │ │
│ /logout │ HEAD,GET │ Proj/Masters/UserController.logout │ auth │ /logout │ │
│ /user │ HEAD,GET │ Proj/Masters/UserController.index │ auth │ user.index │ │
│ /user/create │ HEAD,GET │ Proj/Masters/UserController.create │ auth │ user.create │ │
│ /user │ POST │ Proj/Masters/UserController.store │ auth │ user.store │ │
│ /user/:id │ HEAD,GET │ Proj/Masters/UserController.show │ auth │ user.show │ │
│ /user/:id/edit │ HEAD,GET │ Proj/Masters/UserController.edit │ auth │ user.edit │ │
│ /user/:id │ PUT,PATCH │ Proj/Masters/UserController.update │ auth │ user.update │ │
│ /user/:id │ DELETE │ Proj/Masters/UserController.destroy │ auth │ user.destroy │ │
│ /user │ PUT │ Proj/Masters/UserController.updateAll │ auth │ user.updateAll │ │
│ /user │ DELETE │ Proj/Masters/UserController.destoryAll │ auth │ user.destoryAll │ │
│ /reference │ HEAD,GET │ Proj/Masters/ReferenceController.index │ auth │ reference.index │ │
│ /reference/create │ HEAD,GET │ Proj/Masters/ReferenceController.create │ auth │ reference.create │ │
│ /reference │ POST │ Proj/Masters/ReferenceController.store │ auth │ reference.store │ │
│ /reference/:id │ HEAD,GET │ Proj/Masters/ReferenceController.show │ auth │ reference.show │ │
│ /reference/:id/edit │ HEAD,GET │ Proj/Masters/ReferenceController.edit │ auth │ reference.edit │ │
│ /reference/:id │ PUT,PATCH │ Proj/Masters/ReferenceController.update │ auth │ reference.update │ │
│ /reference/:id │ DELETE │ Proj/Masters/ReferenceController.destroy │ auth │ reference.destroy │ │
│ /reference │ PUT │ Proj/Masters/ReferenceController.updateAll │ auth │ reference.updateAll │ │
│ /reference │ DELETE │ Proj/Masters/ReferenceController.destoryAll │ auth │ reference.destoryAll │ │
│ /country_code │ HEAD,GET │ Common/CountryCodeController.index │ │ country_code.index │ │
│ /country_code/create │ HEAD,GET │ Common/CountryCodeController.create │ │ country_code.create │ │
│ /country_code │ POST │ Common/CountryCodeController.store │ │ country_code.store │ │
│ /country_code/:id │ HEAD,GET │ Common/CountryCodeController.show │ │ country_code.show │ │
│ /country_code/:id/edit │ HEAD,GET │ Common/CountryCodeController.edit │ │ country_code.edit │ │
│ /country_code/:id │ PUT,PATCH │ Common/CountryCodeController.update │ │ country_code.update │ │
│ /country_code/:id │ DELETE │ Common/CountryCodeController.destroy │ │ country_code.destroy │ │
│ /geolocation │ HEAD,GET │ Common/GeolocationController.index │ │ geolocation.index │ │
│ /geolocation/create │ HEAD,GET │ Common/GeolocationController.create │ │ geolocation.create │ │
│ /geolocation │ POST │ Common/GeolocationController.store │ │ geolocation.store │ │
│ /geolocation/:id │ HEAD,GET │ Common/GeolocationController.show │ │ geolocation.show │ │
│ /geolocation/:id/edit │ HEAD,GET │ Common/GeolocationController.edit │ │ geolocation.edit │ │
│ /geolocation/:id │ PUT,PATCH │ Common/GeolocationController.update │ │ geolocation.update │ │
│ /geolocation/:id │ DELETE │ Common/GeolocationController.destroy │ │ geolocation.destroy │ │
│ /time_zone │ HEAD,GET │ Common/TimeZoneController.index │ │ time_zone.index │ │
│ /time_zone/create │ HEAD,GET │ Common/TimeZoneController.create │ │ time_zone.create │ │
│ /time_zone │ POST │ Common/TimeZoneController.store │ │ time_zone.store │ │
│ /time_zone/:id │ HEAD,GET │ Common/TimeZoneController.show │ │ time_zone.show │ │
│ /time_zone/:id/edit │ HEAD,GET │ Common/TimeZoneController.edit │ │ time_zone.edit │ │
│ /time_zone/:id │ PUT,PATCH │ Common/TimeZoneController.update │ │ time_zone.update │ │
│ /time_zone/:id │ DELETE │ Common/TimeZoneController.destroy │ │ time_zone.destroy │ │
│ / │ GET,HEAD │ Closure │ │ / │ │

Sorry I planed to reply yesterday but git showed some error on posting comment

**Comment by hariprasath-yadav** [comment] 2020-02-20 11:11
thank you for edited the content, now i edited it to view more convenient
and if you checked and found the solution please reply to me as soon as possible
i'm eagerly waiting and my works have been stopped because of this.
And sorry to mention it, i also worked on laravel before, i used routes like this and in there its working fine only.

**Comment by thetutlage** [comment] 2020-02-20 13:45
I created a sample project and registered the same set of routes and it seems to working fine. Here is the repo for the project https://github.com/thetutlage/adonis-framework-issue-1207

Can you please use this and help me reproduce the issue?

**Comment by hariprasath-yadav** [comment] 2020-02-21 09:48
Thank You, Yes its worked now
and in my project also its works fine now, but i don't know why it showed the error before.
Is there any cache like in laravel to clear for config, view and so on.

**Comment by hariprasath-yadav** [comment] 2020-02-27 07:53
This same error occurred in my vps when i uploaded my application, i think the new adonis application with these routes works fine but if we added routes to the existing adonis application it can't find the routes, please give me the solution to clear the error. if it is a cache how to clear it

**Comment by thetutlage** [comment] 2020-03-02 02:34
There is no cache. It's hard to tell, why it is breaking in your app, until I am able to reproduce it myself. So please share a project in which I can reproduce this error

**Comment by Kaperskyguru** [comment] 2020-03-07 23:47
@hariprasath-yadav How can we reproduce the your issues. Or use this repo to see if it solves your problem. https://github.com/thetutlage/adonis-framework-issue-1207

**Comment by thetutlage** [comment] 2020-03-08 05:08
Closing since not actionable

**Closed by thetutlage** 2020-03-08 05:08 UTC
Labels: Type: Question
