### ISSUE TITLE
Multiple file upload doesn't validate extension types

### ISSUE THREAD

**Issue by TheAdamGalloway** [adonisjs/core#4072] opened 2023-02-20 12:21 UTC
When using request.files() to upload multiple files in one request, the file extensions aren't validated. This is when using the FileValidationOptions rather than using validator. See sample code.

## Package version
5.8.3

## Node.js and npm version
Node 17.1.0; npm 8.1.4

## Sample Code (to reproduce the issue)
`const images = ctx.request.files('photos', {
      size: '20mb',
      extnames: ['jpg', 'png', 'jpeg'],
    })
console.log(images[0])`

Then test the route with a file other than an image and it won't throw an error.

**Comment by thetutlage** [comment] 2023-02-20 12:56
The `request.files` method does not throw an error. You will have to access the errors using the file.errors property.

Also, it will nice if you share a complete example or a project to reproduce the issue further

**Comment by thetutlage** [comment] 2023-02-25 02:31
Yup, because the `errors` property exists on individual files and `request.files` returns an array of files.

This is how roughly the code should look like

```ts
const images = ctx.request.files('photos', {
  size: '20mb',
  extnames: ['jpg', 'png', 'jpeg'],
})

if(!images.length) {
  return
}

const invalidImages = images.find((image) => image.hasErrors)
if (invalidImages.length) {
  return
}

for (let i = 0; i < images.length; i++) {
  const image = images[i]
  await image.moveToDisk('', {}, 's3')
}
```

Closing issue, it is not a bug. Please use discussions forum to ask questions :)

**Closed by thetutlage** 2023-02-25 02:31 UTC
