### ISSUE TITLE
created_at not giving date time with microsecond precision despite changing the migration file

### ISSUE THREAD

**Issue by rajat-devslane** [adonisjs/core#3386] opened 2021-12-03 07:56 UTC
## Package version

```
"@adonisjs/core": "^5.3.0",
"@adonisjs/lucid": "^16.2.2",
"@adonisjs/repl": "^3.1.0",
"@adonisjs/view": "^6.1.1",
```
## Node.js and npm version
Node: v14.17.6
NPM: 6.14.15

## Issue
I created a migration file and added the created_at column with the precision of 6 but still, it is not returning the fractional part of seconds when we query the table

Changes in migration file from this:

```
...

table.timestamp('created_at', { useTz: true });

...
  
```

To this:

```
...

table.timestamp('created_at', { useTz: true, precision: 6 });

...
```

Output when I query the database the created_at look like this, there is no fractional value of the second

`
created_at: '2021-12-03T12:36:05.000+05:30'
`

Note: When I create a new entry in Table using the "create" method the print is serialized value then "created_at" contains the second's fractional value, like this:

`created_at: '2021-12-03T12:40:46.736+05:30'`

The issue occurs only when we run the fetch query to retrieve the rows from the database.

**Comment by thetutlage** [comment] 2021-12-03 08:23
Duplicate of https://github.com/adonisjs/lucid/issues/748

**Closed by thetutlage** 2021-12-03 08:23 UTC
