### ISSUE TITLE
[ioredis] Unhandled error event: Error: connect ECONNREFUSED 127.0.0.1:6379

### ISSUE THREAD

**Issue by hsunny3993** [adonisjs/core#1203] opened 2020-02-13 18:57 UTC
I've deployed my app on heroku and installed redis addon there.
I have a problem to connect with adonisjs-redis into heroku redis.
Please help me asap.

This is error I got.
![image](https://user-images.githubusercontent.com/57086840/74468258-97b7ca00-4eab-11ea-8568-593f7552cd71.png)

Redis is running on heroku.
![image](https://user-images.githubusercontent.com/57086840/74468355-c5047800-4eab-11ea-84b9-ada3e0e3bf30.png)

**Comment by Kaperskyguru** [comment] 2020-03-07 23:54
@hsunny3993 Is this been resolved, if not how can we reproduced the issues, because I have deployed an Adonisjs application to heroku with redis. I didn't experience that connection problem.

**Comment by thetutlage** [comment] 2020-04-14 06:38
Closing since not actionable

**Closed by thetutlage** 2020-04-14 06:38 UTC
Labels: triage
